### ISSUE TITLE
ProofGeneral stops printing Goal state on Coq error

### ISSUE THREAD

**Issue by HeikoBecker** [ProofGeneral/PG#235]
I am runnning Coq 8.7.2 and the latest ProofGeneral master. 
The issue occurs on large files that contain a proof that cannot be finished when running C-c C-b and needs to be fixed manually.
I also have to step back to the beginning of the buffer and then consume manually until the point where the proof breaks using C-c C-n.

Here is a minimal emacs config that can be used to showcase the problem:

     ;;Proof General
     ;; Open .v files with Proof General's Coq mode
     (load "~/.emacs.d/lisp/PG/generic/proof-site")

and a test file (test.v):

    Definition test (a:nat) (b:nat) := a.
    
    Lemma test_is_a :
      forall a b, test a b = a.
    Proof.
      intros.
      unfold test2.
      auto.

When pressing C-c C-b to evaluate the buffer, Coq will complain that `test2` cannot be unfolded.
When stepping back until the beginning of the Lemma the `*goals*` buffer is not refreshed and stays empty. I can however print the state with C-c C-p. Stepping one step further in the proof will not continue displaying the goal.

To get `*goals*` to display goals again, I have to step back before the definition of `test` and then run over the file stepwise with C-c C-n.

**Comment by Matafou** [comment]
Hi,
I can't reproduce the bug with latest pg/master. But I can with an older version of pg, are you sure you are up to date?.

**Comment by HeikoBecker** [comment]
I get the error when using 
    
    commit 5e7566e54842fb198a6f68abb7c624b53a488038
    Author: Erik Martin-Dorel <erik@martin-dorel.org>
    Date:   Tue Feb 20 10:30:00 2018 +0100

    Bind C-c C-m (= C-c RET) to proof-goto-point [tty] (#228)

    Close ProofGeneral/PG#31

**Comment by Matafou** [comment]
I can reproduce this bug.
I will try to have look. I thought this was fixed.

**Comment by Matafou** [comment]
Sorry I thought I reproduce ths bug but now I can't reproduce it again. This bug is supposed to have been fixed ("Unset Silent." inserted after each backtracking command) 6 month ago.

I see that you have the git version of pg. Do you compile it? If yes did you compile the last version you pulled?

**Comment by HeikoBecker** [comment]
This seems strange. I am using the git version and never compiled it before. For the sake of testing I ran "make clean; make" in the proof general directory. But the bug still persists.

I guess you are referring to the function ``coq-empty-action-list`` for the "Unset Silent.".
When I evaluate the buffer using C-c C-b until it fails, *coq* contains the following information after backtracking until the start of the lemma in the sample file:

    <prompt>Coq < 3 || 0 < </prompt>Add Search Blacklist "Private_" "_subproof". 
    <prompt>Coq < 4 || 0 < </prompt>Set Printing Depth 50 . 
    <prompt>Coq < 5 || 0 < </prompt>Remove Search Blacklist "Private_" "_subproof".  Add Search Blacklist "Private_" "_subproof". 
    <prompt>Coq < 6 || 0 < </prompt>
    <prompt>Coq < 7 || 0 < </prompt>Set Printing Width 115.
    <prompt>Coq < 8 || 0 < </prompt>Set Silent. 
    <prompt>Coq < 9 || 0 < </prompt>Definition test (a:nat) (b:nat) := a.
    <prompt>Coq < 10 || 0 < </prompt>Lemma test_is_a :   forall a b, test a b = a.
    <prompt>test_is_a < 11 |test_is_a| 0 < </prompt>Proof.
    <prompt>test_is_a < 12 |test_is_a| 0 < </prompt>intros.
    <prompt>test_is_a < 13 |test_is_a| 0 < </prompt>unfold test2.
    Toplevel input, characters 7-12:
    > unfold test2.
    >        ^^^^^
    Error: The reference test2 was not found in the current environment.
    <prompt>test_is_a < 13 |test_is_a| 0 < </prompt>Unset Silent. 
    <prompt>test_is_a < 16 |test_is_a| 0 < </prompt>Backtrack 12 0 0 . 
    <prompt>test_is_a < 12 |test_is_a| 0 < </prompt>Backtrack 11 0 0 . 
    <prompt>test_is_a < 11 |test_is_a| 0 < </prompt>Backtrack 10 0 1 . 
    <prompt>Coq < 10 || 0 < </prompt>Set Printing Width 115.
    <prompt>Coq < 20 || 0 < </prompt>Lemma test_is_a :   forall a b, test a b = a.
    <prompt>test_is_a < 21 |test_is_a| 0 < </prompt>

If I now manually put once "Unset Silent." into the *coq* buffer, everything works again as expected.

**Comment by HeikoBecker** [comment]
After a manual investigation I found that somehow the old Debian version of ProofGeneral got installed on my system. After removing it the bug has disappeared. Sorry for any inconvenience or trouble I may have caused.

**Comment by Matafou** [comment]
I am relieved :). No worries.
